const quizData = {
  numberOfQuestions: 10,
  numberOfCorrectAnswers: 6,
  numberOfIncorrectAnswers: 4,
  questions: [
    {
      _id: "6643315600e69db78f80fcb0",
      question: "I enjoy tennis",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["To play", "Plays", "Playing", "To playing"],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "The part of the sentence “I enjoy to play” is not grammatically correct in written English. Instead, you would need to use the correct structure: “I enjoy playing”.",
      point: "1",
      __v: 0,
      questionIndex: 1,
    },
    {
      _id: "6643315600e69db78f80fcd6",
      question:
        "The number of friends and family members at the party amazing.",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["A. Was", "B. Were", "C. Had", "D. Have had"],
      correctAnswer: "1",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "‘was’ is a singular verb used according to the single unit ‘ the number of’.",
      point: "1",
      __v: 0,
      questionIndex: 2,
    },
    {
      _id: "6643315600e69db78f80fc6c",
      question: "We have to get up early",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["On", "In", "At", "During"],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "We use ‘in’ with morning, afternoon, evening and night, but we use ‘on’ when we talk about a specific morning, afternoon, etc.",
      point: "1",
      __v: 0,
      questionIndex: 3,
    },
    {
      _id: "6643315600e69db78f80fcb6",
      question: "Most people agree that kindergarten contributes",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["On", "To", "Among", "Of"],
      correctAnswer: "2",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "We use the preposition “to” after the word contribute or contributes.",
      point: "1",
      __v: 0,
      questionIndex: 4,
    },
    {
      _id: "6643315600e69db78f80fc7e",
      question: "What is the synonym for the word ‘ephemeral’?",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Eternal", "Temporary", "Permanent", "Endless"],
      correctAnswer: "2",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "Ephemeral means something that is temporary or lasts for a very short time.",
      point: "1",
      __v: 0,
      questionIndex: 5,
    },
    {
      _id: "6643315600e69db78f80fc8c",
      question: "He’s grieving his deceased father.",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["A. At", "B. For", "C. On", "D. Over"],
      correctAnswer: "2",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "Grieve means “to feel very sad, especially because somebody has died”. “For” is used when grieving for people. “over” is used when grieving for things.",
      point: "1",
      __v: 0,
      questionIndex: 6,
    },
    {
      _id: "6643315600e69db78f80fcbe",
      question: "Sher khan is playing",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["In", "On", "At", "Off"],
      correctAnswer: "2",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "Use on with days of the week (e.g., on Sunday, on Monday, and so on).",
      point: "1",
      __v: 0,
      questionIndex: 7,
    },
    {
      _id: "6643315600e69db78f80fc72",
      question:
        "The railway system is very efficient as the train always arrives __time.",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Up", "For", "At", "On"],
      correctAnswer: "4",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "We use ‘at’ before time when we mention a specific time. As in — at 5 o’ clock.",
      point: "1",
      __v: 0,
      questionIndex: 8,
    },
    {
      _id: "6643315600e69db78f80fc9c",
      question: "The principal has forbidden smoking on the campus.",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "A. Smoking has been forbidden on the campus by the principal",
        "B. Smoking had been forbidden on the campus by the principal",
        "C. Smoking was being forbidden on the campus by the principal",
        "D. It is forbidden by the principal to smoke in the camps",
        "E. Not change",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "In the present perfect form with the passive, we always use ‘has/have been’ + the past participle form”.",
      point: "1",
      __v: 0,
      questionIndex: 9,
    },
    {
      _id: "6643315600e69db78f80fc94",
      question: "I insist statement.",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["A. For", "B. At", "C. On", "D. In"],
      correctAnswer: "3",
      messageForCorrectAnswer: "Correct answer. Good job.",
      messageForIncorrectAnswer: "Incorrect answer. Please try again.",
      explanation:
        "The standard preposition to use after insist is “on”. For example “I insist on knowing the truth”",
      point: "1",
      __v: 0,
      questionIndex: 10,
    },
  ],
  userInput: [3, 2, 2, 2, 2, 2, 2, 4, 3, 1],
  totalPoints: 10,
  correctPoints: 6,
};

export default quizData;
